default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: app_development
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: app_test
